name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test
          # These options enable proper Docker-in-Docker functionality
          privileged: true
          env: |
            DOCKER_BUILDKIT=1
            DOCKER_HOST=unix:///var/run/docker-host.sock